### ISSUE TITLE
Text labels in an angle of 90°?

### ISSUE THREAD

**Issue by sanojb99** [Silmathoron/mpl_chord_diagram#16]
Is it possible to draw the text labels in an angle of 90°?

**Comment by Silmathoron** [comment]
Hi there!
Yes, this is what the keyword argument ``rotate_names`` is for, you can just enter ``rotate_names=True``.
There is currently a glitch in the Pypi version if you have many entries, but it is fixed on master.

**Comment by sanojb99** [comment]
Got it! Thank you for your answer 👍

**Comment by Silmathoron** [comment]
You're welcome!
