### ISSUE TITLE
Explain 'show' parameter in the documentation

### ISSUE THREAD

**Issue by uguryavuz** [Silmathoron/mpl_chord_diagram#19]
This is certainly a very minor issue, but I couldn't help but notice that all the parameters of `chord_diagram` were explained in [README.md](https://github.com/Silmathoron/mpl_chord_diagram/blob/master/README.md), except for `show`. Perhaps this could be added to the documentation?

**Comment by Silmathoron** [comment]
Indeed, I'll fix that, thank for reporting it.
